#!/bin/bash

set -eux

ROOT="$PWD"
VERSION="$(cat ${ROOT}/github-release/version)"
SOURCE_TAR="${ROOT}/github-release/v${VERSION}.tar.gz"
OUTPUT_FILE=${ROOT}/homebrew-tap/wl.rb

wget \
  -O "${SOURCE_TAR}" \
  "https://github.com/robdimsdale/wl/archive/v${VERSION}.tar.gz"

sha256=$( shasum -a 256 ${SOURCE_TAR} | awk '{ print $1}' )

cat << EOF > ${OUTPUT_FILE}
require "language/go"

class Wl < Formula
  desc "golang wunderlist client"
  homepage "https://github.com/robdimsdale/wl"
  version "${VERSION}"
  url "https://github.com/robdimsdale/wl/archive/v#{version}.tar.gz"
  sha256 "${sha256}"

  depends_on "go" => :build

  go_resource "github.com/tools/godep" do
    url "https://github.com/tools/godep.git", :revision => "2c6ee5e071cf01a41359e33502b7fe79a5801b9e"
  end

  def install
    ENV["GOPATH"] = buildpath
    mkdir_p buildpath/"src/github.com/robdimsdale/"
    ln_sf buildpath, buildpath/"src/github.com/robdimsdale/wl"
    Language::Go.stage_deps resources, buildpath/"src"

    cd "src/github.com/tools/godep" do
      system "go", "install"
    end

    system "./bin/godep", "go", "build", "-o", "wl", "-ldflags", "-X main.version=#{version}", "./cmd/wl/"
    bin.install "wl"
  end

  test do
    system "#{bin}/wl", "--version"
  end
end
EOF

echo "wrote formula successfully"

echo "creating commit in homebrew-tap"
pushd "${ROOT}/homebrew-tap"
  git config user.name "Concourse CI"
  git config user.email "ci@robdimsdale.com"
  git add -v -A .
  git commit -v -m"Update wl to version ${VERSION}"
popd
