#!/bin/bash

set -eux

ROOT="$PWD"
VERSION="$(cat version/number)"
TARGET_GOOS=${TARGET_GOOS:?}
TARGET_GOARCH=${TARGET_GOARCH:?}

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives two directories below the base directory.
BASE_DIR="$( cd ${MY_DIR}/../.. && pwd )"

pushd ${BASE_DIR}
  mkdir -p $GOPATH/src/github.com/robdimsdale
  ln -s $PWD $GOPATH/src/github.com/robdimsdale/wl

  go get -u github.com/tools/godep
  
  godep restore

  IFS='-' read -ra arrVERSION <<< "${VERSION}"
  stripped_version="${arrVERSION[0]}"

  GOOS="${TARGET_GOOS}" \
  GOARCH="${TARGET_GOARCH}" \
  CGO_ENABLED=0 \
  go build \
    -o "${ROOT}"/wl-"${TARGET_GOOS}-${TARGET_GOARCH}-${VERSION}" \
    -ldflags "-X main.version=${stripped_version}" \
    ./cmd/wl/main.go
popd
