#!/bin/bash

set -eux

root_dir="$PWD"

# Outputs
RELEASE_CANDIDATE_DIR="${root_dir}/${RELEASE_CANDIDATE_DIR:?"\$RELEASE_CANDIDATE_DIR not set"}"

VERSION="$(cat version/number)"
TARGET_GOOS=${TARGET_GOOS:?}
TARGET_GOARCH=${TARGET_GOARCH:?}

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives two directories below the base directory.
base_dir="$( cd "${my_dir}/../.." && pwd )"

pushd "${base_dir}"
  mkdir -p "${GOPATH}/src/github.com/robdimsdale"
  ln -s "${PWD}" "${GOPATH}/src/github.com/robdimsdale/wl"

  go get -u github.com/tools/godep

  godep restore

  IFS='-' read -ra arrVERSION <<< "${VERSION}"
  stripped_version="${arrVERSION[0]}"

  GOOS="${TARGET_GOOS}" \
  GOARCH="${TARGET_GOARCH}" \
  CGO_ENABLED=0 \
  go build \
    -o "${RELEASE_CANDIDATE_DIR}/wl-${TARGET_GOOS}-${TARGET_GOARCH}-${VERSION}" \
    -ldflags "-X main.version=${stripped_version}" \
    ./cmd/wl/main.go
popd
