#!/bin/bash

set -eux

root_dir="$PWD"
VERSION="$(cat version/number)"
TARGET_GOOS=${TARGET_GOOS:?}
TARGET_GOARCH=${TARGET_GOARCH:?}

mv \
  wl-release-"${TARGET_GOOS}-${TARGET_GOARCH}"/wl-* \
  "${root_dir}/wl-${TARGET_GOOS}-${TARGET_GOARCH}-${VERSION}"
