#!/bin/bash

set -eux

root_dir="$PWD"

# Outputs
FINALIZED_DIR="${root_dir}/${FINALIZED_DIR:?"\$FINALIZED_DIR not set"}"

VERSION="$(cat version/number)"
TARGET_GOOS=${TARGET_GOOS:?}
TARGET_GOARCH=${TARGET_GOARCH:?}

mv \
  wl-release-"${TARGET_GOOS}-${TARGET_GOARCH}"/wl-* \
  "${FINALIZED_DIR}/wl-${TARGET_GOOS}-${TARGET_GOARCH}-${VERSION}"
