#!/bin/bash

set -eux

ROOT="$PWD"
VERSION="$(cat version/number)"
TARGET_GOOS=${TARGET_GOOS:?}
TARGET_GOARCH=${TARGET_GOARCH:?}

mv wl-release-"${TARGET_GOOS}-${TARGET_GOARCH}"/wl-* "${ROOT}"/wl-"${TARGET_GOOS}-${TARGET_GOARCH}-${VERSION}"
