// This file was generated by counterfeiter
package fakes

import (
	"github.com/robdimsdale/wundergo"
	"sync"
)

type FakeLogger struct {
	PrintlnStub        func(message string)
	logLineMutex       sync.RWMutex
	logLineArgsForCall []struct {
		message string
	}
}

func (fake *FakeLogger) Println(message string) {
	fake.logLineMutex.Lock()
	defer fake.logLineMutex.Unlock()
	fake.logLineArgsForCall = append(fake.logLineArgsForCall, struct {
		message string
	}{message})
	if fake.PrintlnStub != nil {
		fake.PrintlnStub(message)
	}
}

func (fake *FakeLogger) PrintlnCallCount() int {
	fake.logLineMutex.RLock()
	defer fake.logLineMutex.RUnlock()
	return len(fake.logLineArgsForCall)
}

func (fake *FakeLogger) PrintlnArgsForCall(i int) string {
	fake.logLineMutex.RLock()
	defer fake.logLineMutex.RUnlock()
	return fake.logLineArgsForCall[i].message
}

var _ wundergo.Logger = new(FakeLogger)
