#!/bin/bash

set -eux

NORACE=${NORACE:-false}
SLOW_SPEC_THRESHOLD=${SLOW_SPEC_THRESHOLD:-10}

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects that it lives one directory below the base directory.
base_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${base_dir}"
  if [ "${NORACE}" = "true" ]; then
    ginkgo \
      -p \
      -r \
      -randomizeAllSpecs \
      -failOnPending \
      -slowSpecThreshold="${SLOW_SPEC_THRESHOLD}" \
      "$@" \
      integration_tests
  else
    ginkgo \
      -p \
      -r \
      -race \
      -randomizeAllSpecs \
      -failOnPending \
      -slowSpecThreshold="${SLOW_SPEC_THRESHOLD}" \
      "$@" \
      integration_tests
  fi
popd
